[package]
name = "geometric_algebra_proc_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
geometric_algebra = { workspace = true }
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"
